### ISSUE TITLE
The name of this expliot is not g-mayonnaise

### ISSUE THREAD

**Issue by lilmayu** [nodusclient/guardian#1]
![](https://cdn.discordapp.com/emojis/585885410257928194.gif?size=96)

Good job tho.

**Comment by meddleh** [comment]
Exactly, why it is named guardian? What a stupid name duh

**Comment by Deathlife23** [comment]
I want it to be gurney, because I'm the Coroner

**Comment by meddleh** [comment]
> I want it to be gurney, because I'm the Coroner

shut mayonnaise is better

**Comment by lilmayu** [comment]
GitHub has real-time updates. Really cool. Why we are even using discord?

**Comment by meddleh** [comment]
> GitHub has real-time updates. Really cool. Why we are even using discord?

Because github was made from microsoft

**Comment by lilmayu** [comment]
> > GitHub has real-time updates. Really cool. Why we are even using discord?
> 
> Because github was made from microsoft

GitHub was bought by M$
> Microsoft acquired its larger rival GitHub in 2018 for $7.5 billion (from some random site)
https://news.microsoft.com/announcement/microsoft-acquires-github/

**Comment by compieter-gh** [comment]
Ew more M$ where my github coins? xd, Anyway is this by any chance patched in 1.19.2?

**Comment by 0xAda** [comment]
yes, this is patched in 1.19.2
