### ISSUE TITLE
Keep player's own messages in their last seens

### ISSUE THREAD

**Issue by Aizistral** [nodusclient/guardian#5]
![image](https://user-images.githubusercontent.com/47505981/183305426-b2a0ab0a-3de8-49ad-a0b9-d526f036ed14.png)

**Comment by joeyjumper94** [comment]
if you had just joined the server, wouldn't your last seen also be empty?

**Comment by Aizistral** [comment]
> if you had just joined the server, wouldn't your last seen also be empty?

Well yes, but you don't rejoin after literally every message. It's all about context, not individual messages.

**Comment by 0xAda** [comment]
done
