### ISSUE TITLE
Feature request - scrambling signatureOfPreviousHeader

### ISSUE THREAD

**Issue by ylyxa** [nodusclient/guardian#6]
Another way to break the chain of reported messages. Replacing `signatureOfPreviousHeader` (and the corresponding entry in `lastSeenSignatures` if #5 is implemented) with random gibberish will make it look like any report containing 2 or more of your messages has some of your messages omitted, even if none actually were.

**Comment by Aizistral** [comment]
That would require server modificaion, no?

**Comment by ylyxa** [comment]
> That would require server modificaion, no?

No, messages you send are made 100% client-side.

**Comment by Aizistral** [comment]
But it doesn't mean there is no server-sided validation. You cannot just randomly break your chains without the server kicking you out, unless you modify the server to not do that.

**Comment by ylyxa** [comment]
Even if there is server-side validation, I think it can be bypassed just as easily: instead of directly replacing `signatureOfPreviousHeader`, automatically send a private message to yourself after (or before) every message you type in chat.

Unless messages you can't see are automatically included in reports. Dunno if they are, but I doubt that.

**Comment by 0xAda** [comment]
guardian now redacts the signatureOfPreviousHeader field in all packets

**Comment by Aizistral** [comment]
> guardian now redacts the signatureOfPreviousHeader field in all packets

But there is nothing to redact since 1.19.3? 😅
