### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by joeyjumper94** [nodusclient/guardian#7]
normally i can just run `cd /d DIRECTORY` to change the directory of the command prompt to where the source files are then run `gradlew build` to compile a project from source but for some reason everything put out by nodusclient is whining about the same thing

```
D:\github\girlboss>gradlew build
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

**Comment by 0xAda** [comment]
looks like I forgot to commit the gradle wrapper, just use your system
installation of gradle, so `gradle build` instead of `gradlew build`

**Comment by 0xAda** [comment]
fixed
